### ISSUE TITLE
inline elements are not indented

### ISSUE THREAD

**Issue by mfiano** [ruricolist/spinneret#10] opened 2017-02-19 07:12 UTC
Elements in `*inline-elements*`, such as `<a>` are not indented at all, and always start at column 0. This looks wrong and makes debugging difficult without client-side tools to reformat the html.

**Comment by PuercoPop** [comment] 2017-02-19 16:46
The issue seems happen after the body tag:

```lisp
(spinneret:with-html (:html (:head)
                            (:body (:a "hai"))))
```

```
<html lang=en>
 <head>
  <meta charset=UTF-8>
 </head>
 <body>
<a>hai</a>
 </body> 
</html>
```

While the following works ok

```lisp
(spinneret:with-html (:ul (:li
                           (:a "hai"))))
```

```
<ul>
 <li><a>hai</a>
</ul>
```

**Comment by mfiano** [comment] 2017-02-19 17:16
Yes, it seems to occur with non-`*paragraph-elements*` the most. However, the following happens with `<li>` and `<a>` (but does not occur with `<div>` and `<a>`), which I still think is wrong. It happens when the inline line is too long:

```lisp
(spinneret:with-html
  (:div
   (:div
    (:div
     (:ul.one-half.column.social
      (:li
       (:a.class1.class2.class3.class4.class5
        :href "hello hello hello")))))))

#| =>
<div>
 <div>
  <div>
   <ul class="one-half column social">
    <li><a class="class1 class2 class3 class4 class5" href="hello hello hello">
     </a>
   </ul>
  </div>
 </div>
</div>
|#
```

**Comment by ruricolist** [comment] 2017-02-19 23:26
Inline elements not indenting is definitely a bug. 

I don't understand, though, what the problem is in the second example (where the inline line is too long). The line has to wrap somewhere. How do you think that should look?

**Comment by mfiano** [comment] 2017-02-20 00:16
@ruricolist It doesn't have to wrap, and infact it already does not wrap with non-inline tags.

**Comment by ruricolist** [comment] 2017-02-22 01:42
I believe I've fixed the problem with elements not getting indented. @mfiano, would you check if it fixes your other problem?

**Comment by mfiano** [comment] 2017-02-22 03:40
@ruricolist The changes fix the bug of not indenting, but does nothing for the other problem. On top of this, I just discovered another similar but more serious problem:

```lisp
(spinneret:with-html (:div "hello" (:a :href "#") "there"))

#|
<div>
hello<a href=#></a>  there
</div>
|#
```

It is very bad that 2 space characters are inserted before "there". I have tried to track down why this is occuring and throwing off my whole html format to no avail.

**Comment by ruricolist** [comment] 2017-02-22 19:43
I've pushed a fix for the extraneous space bug.

**Comment by mfiano** [comment] 2017-02-22 23:24
@ruricolist The extraneous space fix still has some issues that are deeper than I thought.

For example, if an inline tag is wrapped to a new line such as:

```
<a href=/some/url>
title</a>
```

That is actually rendered as:

``` title```

instead of

```title```

This is why I suggested optionally turning off wrapping in #11 
A newline (with 0 or more spaces to follow) is rendered as `&nbsp;`

**Comment by mfiano** [comment] 2017-02-23 05:23
I will not be providing anymore feedback with the pretty printing, as rendering with *print-pretty* as NIL does not have these issues and will allow me to continue my project. Feel free to close this or leave it open as a reminder that pretty printing still needs some work.

**Comment by ruricolist** [comment] 2017-02-23 21:16
Thanks for the testing. And good luck with your project.

**Comment by ruricolist** [comment] 2017-04-07 19:04
At this point, the pretty-printer has been almost completely rewritten, so I'm closing this issue as no longer relevant.

**Closed by ruricolist** 2017-04-07 19:04 UTC
